// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExternalSearch
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidExternalSearchPackageString = "dae52693-5d2f-474e-802a-595dcca337f0";
        public static Guid guidExternalSearchPackage = new Guid(guidExternalSearchPackageString);

        public const string guidExternalSearchPackageCmdSetString = "6e28ef66-3b33-4e5e-88f0-75c389c34b55";
        public static Guid guidExternalSearchPackageCmdSet = new Guid(guidExternalSearchPackageCmdSetString);

        public const string guidImagesString = "a687229c-2231-42ee-9d85-524d0a2f5e45";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int SearchCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}